### ISSUE TITLE
Add system check for presence of required data files

### ISSUE THREAD

**Issue by XanderVertegaal** [UUDigitalHumanitieslab/parseport#29]
Django's system check framework: https://docs.djangoproject.com/en/5.0/topics/checks/

If you do end up using a system check, you could tell the create subset command to ignore system checks (see https://docs.djangoproject.com/en/5.0/howto/custom-management-commands/#django.core.management.BaseCommand.requires_system_checks).

_Originally posted by @bbonf in https://github.com/UUDigitalHumanitieslab/parseport/pull/28#discussion_r1579100632_

**Comment by XanderVertegaal** [comment]
This could also be relevant for SpindleServer (w.r.t. `model_weights.pt`).

**Comment by bbonf** [comment]
I realized system checks were not the right solution for this (partly because they run after `AppConfig.ready()`)
