### ISSUE TITLE
Add Celery + Redis

### ISSUE THREAD

**Issue by XanderVertegaal** [UUDigitalHumanitieslab/parseport#4]
Can we use docker-compose with this, in combination with the cookie-cutter backend (+ frontend)?

**Comment by JeltevanBoheemen** [comment]
See https://github.com/UUDigitalHumanitieslab/sasta/blob/develop/docker-compose.yml and https://github.com/UUDigitalHumanitieslab/I-analyzer/blob/develop/docker-compose.yaml for inspiration. SASTA uses rabbitmq instead of redis, but that's easily adaptable.

**Comment by XanderVertegaal** [comment]
Celery should also periodically clean up any remaining files on the latex-service server (cronjob). Latexmk provides a command for this (`latexmk -C`).

**Comment by XanderVertegaal** [comment]
Instead of Celery/Redis, we can also use crontabs on the server.

**Comment by XanderVertegaal** [comment]
Cronjob set up for all ParsePort servers: `30 2 * * * /usr/bin/docker exec pp-latex sh -c 'latexmk -C && rm *.tex'`
