### ISSUE TITLE
Parser backend status

### ISSUE THREAD

**Issue by bbonf** [UUDigitalHumanitieslab/parseport#8]
Because the spindle container runs in a separate container and takes a while to start, there's a chance that the user sends a requests when the backend isn't ready, and that fails without an explanation.
It would be nice if the app could check the status of spindle (or the relevant parser backend), and prevent the user from sending queries if the parser is not ready.

**Comment by XanderVertegaal** [comment]
The same is true for Aethel now. The frontend should receive a signal when the backend is ready to receive requests.
